### ISSUE TITLE
Incorrect processing of long file paths

### ISSUE THREAD

**Issue by Serg-de-Adelantado** [rokucommunity/vscode-brightscript-language#1]
Brightscript debugger may return trimmed path to source file on [`bt` command](https://github.com/TwitchBronBron/vscode-brightscript-language/blob/3559c91cdeb1c768af335ee4ad5a24ef5b7b9c2c/src/RokuAdapter.ts#L310) for long paths(3 or 4 nested folders), which cause error in VS Code(file not found) and makes impossible further debugging of such a file. AFAIK, there are no commands to disable such behaviour of the debugger(like `set filename-display` in GDB, for example).
In our project we came to using of unique file names and I made a few changes to this extension:
+ added a map with file names as keys and relative paths as values
+ modified the [convertDebuggerPathToClient method](https://github.com/TwitchBronBron/vscode-brightscript-language/blob/3559c91cdeb1c768af335ee4ad5a24ef5b7b9c2c/src/brightScriptDebugSession.ts#L390) to search a file name in this map.

Of course, it is not a solution for project with duplicated file names in different folders, for example:
+ `components/screens/screen1/views/grid/SomeAbstractGrid.brs`
+ `components/screens/screen2/views/grid/SomeAbstractGrid.brs`

So an alternate way to solve this issue may be in replacing of all file names(and their usages in xml files) by UUIDs(or other unique identifiers) with a map storing UUID-file path relation.

**Comment by TwitchBronBron** [comment]
Interesting! I'll try to take a look at this soon and see what I can come up with to solve all of the issues.

**Comment by Serg-de-Adelantado** [comment]
Thank you for the update, it is even better then my current solution, since it may handle duplicates in some cases. It will be a nice addition to print duplicates warning into debug console while [making a map of trimmed paths](https://github.com/TwitchBronBron/vscode-brightscript-language/blob/2c67463f07458595141b830f54480d02d5dd1a4c/src/brightScriptDebugSession.ts#L390).

**Comment by TwitchBronBron** [comment]
I'm closing this ticket. Roku has released a formal socket debugging protocol, which returns the full file path. So, there's not much benefit to updating the hacked-together telnet debugger at this point. We will eventually align with the official socket debugging protocol, and then this will be a non-issue.
