### ISSUE TITLE
Stopping debug does not always kill all active threads

### ISSUE THREAD

**Issue by chrisdp** [rokucommunity/vscode-brightscript-language#116]
When restarting debugging or stopping following a bright script crash it should run the exit command until the "Thread detached" message is detected.

In some cases this leads to the channel getting stuck in an open state and will not accept a new side load. I am able to get around this by opening a telnet connection and running exit my self a few times until I get the "Thread detached" message. After that the channel closes to the home screen correctly and I am able to side load again.

**Comment by TwitchBronBron** [comment]
@triwav this is the same thing we were discussing on slack, right where we decided it would be better to send the kill command instead of the home press? I like the idea of running the exit command repeatedly until we get the "thread detached" message. Thoughts?

**Comment by chrisdp** [comment]
Pr related to this issue: #124

**Comment by chrisdp** [comment]
@triwav Thinking we can call this one fixed? Only time this seems to happen now is if the box is in a really messed up state. But that’s rare now and there’s not a lot we can do about it. Also I think the debug protocol addresses this issue long term.

**Comment by triwav** [comment]
I still see it happen. The fact we now allow you issue your own commands this is way easier to fix by just issuing the quit command yourself

**Comment by TwitchBronBron** [comment]
@chrisdp @triwav is this still an issue?

**Comment by chrisdp** [comment]
I don't think so... @triwav thoughts?
