### ISSUE TITLE
Monitor Roku for closed session and close debugger

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/vscode-brightscript-language#126]
Certain situations cause the Roku app to close, and the debugger is not always aware of that, such as a home button press from a physical remote, or the app encounters a `exit` command.

Roku provides an external control api which would allow us to monitor the running app, and whenever a running app quits, we could kill any active debug session. This would only be activated on debug start, and would be terminated on debug stop. 

https://sdkdocs.roku.com/display/sdkdoc/External+Control+API#ExternalControlAPI-ExternalControlServiceCommands
`query/active-app`

I envision this being some type of polling (every 10 seconds, "is my sideloaded app running?"), and if the app is not running, stop the debug session.

This will also need to be configurable through a setting because some developers will not want to stop their debug session. A boolean "enabled/disabled" flag should be sufficient.

**Comment by georgejecook** [comment]
I'll probs end up doing this.. it drives me nuts

**Comment by TwitchBronBron** [comment]
@georgejecook does #150 resolve this as well?
