### ISSUE TITLE
incorrect reporting of duplicate function

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/vscode-brightscript-language#147]
![Screen Shot 2019-05-04 at 2 51 24 PM](https://user-images.githubusercontent.com/1214545/57184136-37a3ea00-6e7c-11e9-8fbf-ab63335ac057.png)

Getting a ton of errors reporting that a function is a duplicate in global scope, when it isn't.

The file is in the source path, and is included in various components, one of which is then extended by other components.

**Comment by TwitchBronBron** [comment]
There are hard to track down without an example, because in most cases, it's dependent upon multiple factors in your project. Can you provide a working example project or steps to reproduce?

**Comment by TwitchBronBron** [comment]
@georgejecook are you still seeing this as an issue?

**Comment by georgejecook** [comment]
no
