### ISSUE TITLE
Integer values in AAs aren't shown properly on hover

### ISSUE THREAD

**Issue by triwav** [rokucommunity/vscode-brightscript-language#164]
When you have an integer (may effect other values as well) if it's an AA and you try to hover a usage of it it just returns the type not the value as well. In the image I also have direct reference to an integer that does work. Not sure if this because we're not even trying to make a request to 8085 since we know what is or if this specific to AAs
![image](https://user-images.githubusercontent.com/1753881/59949783-2de14080-9442-11e9-993d-e371f5c31a39.png)

**Comment by chrisdp** [comment]
Fixed over time. Closing.
