### ISSUE TITLE
Strings ending with " in AA don't show up right

### ISSUE THREAD

**Issue by triwav** [rokucommunity/vscode-brightscript-language#165]
If a string ends with a " then it doesn't show right both on pop over and vars pane
![image](https://user-images.githubusercontent.com/1753881/59949636-b6131600-9441-11e9-95b8-0f319ec609bf.png)

**Comment by TwitchBronBron** [comment]
@triwav can we close this since the telnet debugger will soon be depricated in favor of the BrightScript debug protocol?
