### ISSUE TITLE
Use bracket notation instead of dot notation for value lookup

### ISSUE THREAD

**Issue by triwav** [rokucommunity/vscode-brightscript-language#166]
If you have an AA like
```
test = {
    "I have": "a space so I won't work right"
    "0": "I'm just a number so I won't work right"
}
```
neither of these will work because we're trying to do something like this 
`print test.I have` or `print test.0` which won't work. There's other cases like if the key had a period in it or some other special character that causes issues as well.

If we instead use bracket notation then it will work
`print test["I have"]` or `print test["0"]`.
Since we're changing this already, you may want to switch to just sending `p` instead of `print`. May be worth doing a search for `"` character as well to avoid the bracket notation from breaking on a string with a quote in it. So instead of sending:
`p test["this has a "quote" so will break unless we escape it"]` which would break
we send
`p test["this has a " + chr(34) + "quote" + chr(34) + " so will break unless we escape it"]` and it should work

**Comment by chrisdp** [comment]
@triwav with us moving to the debug protocol I think we can close this yes?
