### ISSUE TITLE
improve logging for EPIPE errors, or perhaps deployment in general

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/vscode-brightscript-language#176]
This looks like #14; but is different - the telnet session was not inacessible in this case: what happened was that it was connecting to the wrong ip address. I was not made aware to which roku ip it was attempting to connect, so had no other recourse but to debug the extension source - took me an hour, when a brief method of "could not connect to 192.168.0.102" would've sufficed.

perhaps there's some logging here already - or a device selector, in which case, it'd be great to know how to access it.

**Comment by chrisdp** [comment]
I have completed the other items I have been working on so I will attempt to work on this over the following week as it has also been an issue for me.

**Comment by chrisdp** [comment]
Also @georgejecook, the ext has a device selector built in now if you'rr using `"${promptForHost}"`. It scans the network for online devices and when you do a run it will ask you what device to use. If you do a Restart it will use the same device without asking. If you stop and start again the last device you used will be pre-selected.

**Comment by georgejecook** [comment]
this is working fine, with `${promptForHost}`

**Comment by chrisdp** [comment]
PR opened to address this issue #179

**Comment by chrisdp** [comment]
@georgejecook this should be fixed now yes? Can we close this issue?

**Comment by georgejecook** [comment]
fixed. closing
