### ISSUE TITLE
Improve active device picker

### ISSUE THREAD

**Issue by chrisdp** [rokucommunity/vscode-brightscript-language#187]
The idea is to add a status bar item and a extension command to pre-select your active device. 

This would open the same device picker UI that is currently in use but by selecting a device with this approach it would act more like a "remember this device".

The status bar would also reflect some information about what device is currently set as the remembered device.

When a device is selected in this way the extension would no longer ask you what device you want to connect to when starting a debug session.

@georgejecook Thoughts on this as you where talking about how it was a pain for it to keep asking after each session is ended and started again.

**Comment by triwav** [comment]
Makes sense. So I currently use restart to get around this. The only downside would be if someone actually did want to switch each time but if the status bar is easy enough to use then that should work I would think

**Comment by chrisdp** [comment]
@triwav right, also with the proposal if you didn't use the status bar or the extension command it would continue to act the way it does. You would need to intentionally set a device as remembered or would could also add a user set like `brightscript.deviceDiscovery.alwaysRemeberLastUsedDevice`.

**Comment by triwav** [comment]
Ah gotcha. Even better. Sounds like all improvements with no downsides to me then.

**Comment by TwitchBronBron** [comment]
This was implemented in #375
