### ISSUE TITLE
Build in a proxy middleware layer 

### ISSUE THREAD

**Issue by chrisdp** [rokucommunity/vscode-brightscript-language#210]
TDB

**Comment by chrisdp** [comment]
Closing due to the complicated nature of this feature.

**Comment by TwitchBronBron** [comment]
@chrisdp I think this is still a viable option. Might not be the easiest thing to do, but if it will benefit the community then it's totally worth investigating.

**Comment by chrisdp** [comment]
The issue is that there are so many ways to do this and there is. I one way that is going to work well for everyone. Maybe we can look at this down the road but there are solutions out there to there issue. All of them with there own reasons to be used or not.
