### ISSUE TITLE
VSC task 2.0.0 configuration

### ISSUE THREAD

**Issue by zWaR** [rokucommunity/vscode-brightscript-language#214]
Hi there,

I just installed the extension and wanted to give it a try. However, I ran into issues with VSC tasks 2.0.0 configuration. Since the examples in the documentation are for version 0.2.0 I could not use them directly, so I tried something like this:

```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "brs-test-run",
            "type": "brightscript"
        }
    ]
}
```

Unfortunately, even by only defining this, I already get a linter error saying that `brightscript` is not a valid task type. If you could provide me with a VSC tasks 2.0.0 example with the equivalent of the snippet bellow, it would be great:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "brightscript",
            "request": "launch",
            "name": "BrightScript Debug: Launch",
            "host": "192.168.1.17",
            "password": "password",
            "rootDir": "${workspaceFolder}",
            "stopOnEntry": false
        }
    ]
}
```
Thanks!

**Comment by chrisdp** [comment]
@zWaR are you putting this in a tasks.json or the launch.josn?

This should be in the launch.json file.

**Comment by TwitchBronBron** [comment]
@zWaR did that fix your issue?

**Comment by zWaR** [comment]
@TwitchBronBron Yes that fixed it thanks! :)
