### ISSUE TITLE
Improvement to logging

### ISSUE THREAD

**Issue by John-Whitehead** [rokucommunity/vscode-brightscript-language#216]
I think a great new feature would be to have an option to log the OUTPUT, BRIGHTSCRIPT LOG and other windows to an output file on the filesystem for viewing dynamically as it is written, or later on after the session is over.

Right now, once you close VS Code, all that information disappears and is lost.

**Comment by TwitchBronBron** [comment]
I like this idea a lot. We could add an option in user settings (or the launch config) for specifying a logfile location. Then, all of the output sent to the BrightScript log channel could also be appended to that file. The BrightScript output channel would still be cleared on every vscode close, but this way you would at least still have the original output. 

How does that sound?

How does that sound?

**Comment by John-Whitehead** [comment]
Thanks Bronley, that would serve my needs very well.  It is up to you whether it is a user or launch setting, but I think launch.json would be the best place given some projects have multiple launch configs.  I am not expert enough to know for sure though.

**Comment by John-Whitehead** [comment]
Bronley - thanks so much for this.  I finally have a chance to use it now.

**Comment by TwitchBronBron** [comment]
Glad to hear it!
