### ISSUE TITLE
brightscript.debug.logfilePath with ${workspaceFolder} fails with "Cannot read property 'uri' of undefined"

### ISSUE THREAD

**Issue by triwav** [rokucommunity/vscode-brightscript-language#234]
Setting the following in settings fails because ${workspaceFolder} doesn't get converted to the absolute path.
{
	"brightscript.debug.logfilePath": "${workspaceFolder}/out/benchmarks_output.txt"
}
if you use an absolute path it works correctly

**Comment by TwitchBronBron** [comment]
Closing this as we've implemented a new `fileLogging` option that replaces this option.
