### ISSUE TITLE
Snippets very likely confuse snippet-variables and snippet-placeholders

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/vscode-brightscript-language#252]
![image](https://user-images.githubusercontent.com/2544493/83831561-aa058000-a6b5-11ea-8a4b-1e4ce963af4a.png)

@markwpearce do you have any time to investigate this? It shows up anytime I run the extension host (when debugging extension code).

**Comment by markwpearce** [comment]
Yes, I'll take a look
