### ISSUE TITLE
Version 2.5 no longer allows me to run brightscript project.

### ISSUE THREAD

**Issue by arcendu** [rokucommunity/vscode-brightscript-language#261]
After updating to 2.5.0 my project no longer runs. When I start debugging the debugger stops.
When I go back to previous version 2.4.6 project works again.
2.5 does not show anything in the output.

**Comment by TwitchBronBron** [comment]
Does the extension still fail when you debug some of these sample projects? 

https://github.com/rokucommunity/sample-projects

**Comment by TwitchBronBron** [comment]
I think this was related to #259 and should be fixed in [v2.5.4](https://github.com/rokucommunity/vscode-brightscript-language/releases/tag/v2.5.4). Feel free to re-open if there are further issues.

**Comment by arcendu** [comment]
Outstanding it works great! Thanks @TwitchBronBron

**Comment by TwitchBronBron** [comment]
Great, thanks for the update!
