### ISSUE TITLE
Incorrect root dir used in certain prelaunch use cases

### ISSUE THREAD

**Issue by pixshatterer** [rokucommunity/vscode-brightscript-language#273]
Seems like `rootDir` path must exist even if In certain cases `rootDir` path is expected to be created during `preLaunchtask` execution.   If `rootDir` doesn’t exist beforehand, it takes `${workspace}` as fallback root folder, even if `preLaunchtask` was able to successfully create it before debug session starts.

**Comment by TwitchBronBron** [comment]
This has been fixed in [v2.8.1](https://github.com/rokucommunity/vscode-brightscript-language/releases/tag/v2.8.1)
