### ISSUE TITLE
After update 14.08.2020 - Has a problem with rootDir 

### ISSUE THREAD

**Issue by Semenone** [rokucommunity/vscode-brightscript-language#274]
After update 14.08.2020 - Has a problem with rootDir (rootDir does not exist at "/rokuapp") with paths "rootDir": "../../rokuapp" and "rootDir": "~Downloads/rokuapp". Trying on MacOS Catalina 10.15.6 and Windows 10. On Windows it looks for the file in an unknown order, and if it does find it, then (connect ECONNREFUSED 192.168.0.100:8060) - it my host("host": "192.168.0.100",)

**Comment by TwitchBronBron** [comment]
Hey, sorry for the late response on this. Are you still having issues with the latest release?

**Comment by TwitchBronBron** [comment]
I believe we resolved this issue in a previous release, so I'm closing this.
