### ISSUE TITLE
[windows & mac] error validating workspace: cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by FrederickEngelhardt** [rokucommunity/vscode-brightscript-language#277]
Popup reads as followed. Is there a way to disable this popup?
```
Critical error validating workspace: Cannot read property 'toLowerCase' of undefined
```

Currently using brighterscript. Was not getting this error a couple days ago...

**Comment by FrederickEngelhardt** [comment]
Closing. Looks like I missed an XML closing tag which resulted in this issue.

**Comment by TwitchBronBron** [comment]
Yikes! Could you provide the xml file that was missing the closing tag? I definitely want to find the issue causing those popups, and prevent them.
