### ISSUE TITLE
"View transpiled file" preview should include plugin manipluations

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/vscode-brightscript-language#280]
currently we get the raw brighterscript; what a joy and aid to plugin developers if we could see the actualy code as roku-deploy will write, post plugin manipulations. I'd see this being useful for brs, xml and bs files.

**Comment by TwitchBronBron** [comment]
The way I understand it, it should be that way already. We call file.transpile() at the time of you clicking the "view preview" button, so if the plug-in has manipulated the ast, you will see it in the preview.

**Comment by georgejecook** [comment]
this is not the case.

**Comment by TwitchBronBron** [comment]
Can you please list all of the plugin hooks you are using.

**Comment by chrisdp** [comment]
@TwitchBronBron this was added recently correct?

**Comment by TwitchBronBron** [comment]
Yes.
