### ISSUE TITLE
2-way "view transpiled file" preview window click sync 

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/vscode-brightscript-language#282]
currently only does nav sync when clicking somewhere in source; would be awesome to click a transpiled line and have the source pane navigate to it.

**Comment by TwitchBronBron** [comment]
There is already logic to handle this. https://github.com/rokucommunity/vscode-brightscript-language/blob/736264d7f53e953fcdd9c42b852cf592dd9ddfd1/src/commands/BrighterScriptPreviewCommand.ts#L48
