### ISSUE TITLE
Publish extension to open-vsx.org

### ISSUE THREAD

**Issue by DusanLesan** [rokucommunity/vscode-brightscript-language#283]
Hello. Could you please publish brightscript-language extension to open-vsx.org in addition to the VS Code Marketplace.
This will allow VSCodium users to find your extension.

**Comment by TwitchBronBron** [comment]
Sure! I'll look into this. Thanks for asking. :)

**Comment by TwitchBronBron** [comment]
@DusanLesan Done! 

https://open-vsx.org/extension/RokuCommunity/brightscript

**Comment by DusanLesan** [comment]
> @DusanLesan Done!
> 
> https://open-vsx.org/extension/RokuCommunity/brightscript

Thanks. My VS Code did automatic update on it's own now

**Comment by TwitchBronBron** [comment]
@DusanLesan I just wanted to check in and see how the open-vsx releases have been working for you? All good?

**Comment by DusanLesan** [comment]
> @DusanLesan I just wanted to check in and see how the open-vsx releases have been working for you? All good?

Thank you very much for checking. Everything is alright. The latest version is available for me (2.14.0)

**Comment by TwitchBronBron** [comment]
Great, glad to hear it! Thanks.
