### ISSUE TITLE
MOD is not colored like other operators

### ISSUE THREAD

**Issue by chrisdp** [rokucommunity/vscode-brightscript-language#284]
![image](https://user-images.githubusercontent.com/9591618/99541060-bb51f880-2986-11eb-844e-e2d7dfa8464e.png)

compared to the following:
![image](https://user-images.githubusercontent.com/9591618/99541237-f3593b80-2986-11eb-8074-e59b35bff936.png)

**Comment by TwitchBronBron** [comment]
Mod wasn't even included in the syntax highlighting file for some reason. This has been fixed and will be included in the next release.
