### ISSUE TITLE
Console pops up with error messages on save

### ISSUE THREAD

**Issue by lkipke** [rokucommunity/vscode-brightscript-language#290]
Hello,

Whenever I save a `.brs` file in my project with this extension enabled, the console output pops up and displays a bunch of error messages:
![Screen Shot 2021-01-29 at 2 16 08 PM](https://user-images.githubusercontent.com/11684087/106332991-a7572c80-623c-11eb-864f-341dd6c7cc4d.png)

This is particularly frustrating, because I don't normally have the console open -- it appears that the extension is popping it open on its own. I'm also not using brighterscript, just normal brightscript. Thank you for any help 😄

**Comment by TwitchBronBron** [comment]
Hey, we must have introduced a bug in the language server recently. Both BrightScript and BrighterScript use the BrighterScript language server to provide `goto`, function hints, completions, etc. Do you know if there's any specific action that causes this to happen regularly? I'd like to try and reproduce it on my machine so I can get to the bottom what is causing the errors.

**Comment by TwitchBronBron** [comment]
I found the issue. I submitted [BrighterScript PR #294](https://github.com/rokucommunity/brighterscript/pull/294), so this should get released in the next day or two.

**Comment by TwitchBronBron** [comment]
Release v2.14.1 fixes this issue. Give it a try and let me know if you still see any issues.
