### ISSUE TITLE
Cannot read property 'getCodeActions' of undefined

### ISSUE THREAD

**Issue by chrisdp** [rokucommunity/vscode-brightscript-language#295]
I haven't had time to see if this is still an issue on the latest release but it was not in the patch notes. This is an error I have been seeing lately in the BrighterScript Language Server Logs. I unfortunately do not have steps to replicate as this has been sporadic but frequent. 

```
[Error - 6:27:32 PM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Cannot read property 'getCodeActions' of undefined
  Code: -32603 
```

**Comment by TwitchBronBron** [comment]
I believe this issue has been resolved, so I'm closing.
