### ISSUE TITLE
outDir required and staging dir empty - Issues with 2.22.1

### ISSUE THREAD

**Issue by Puritanic** [rokucommunity/vscode-brightscript-language#314]
It looks like there are some issues with the latest release. Deploying app to the device now requires that we have `outDir` field added to VSCode launch.json. It's working without it in 2.22.0.

My launch task:

```JSON
		{
			"envFile": "${workspaceFolder}/.env",
			"type": "brightscript",
			"request": "launch",
			"name": "BrightScript Debug: Launch env",
			"host": "${env:ROKU_DEV_TARGET}",
			"password": "${env:ROKU_DEV_PASSWORD}",
			"rootDir": "${workspaceFolder}/src",
			"stopOnEntry": false,
			"stopDebuggerOnAppExit": false,
			"enableDebuggerAutoRecovery": true,
			"injectRaleTrackerTask": true
		}
```
With this, I'm receiving this error:

> outDir is required

If I add `outDir` to the task above (`"outDir": "${workspaceFolder}/out"`), then I'm receiving this error:

> Cannot zip package: missing manifest file in "/Users/dtasevski/roku/out/.roku-deploy-staging"

By setting the `retainStagingFolder` field to true, I can see that the staging directory is empty. I have no idea where to go from here, but it looks like upgrade to the latest roku-deploy caused this for some reason.

My bsconfig.json:

```JSON
{
	"rootDir": "./src",
	"watch": false,
	"files": [
		"components/**/*.*",
		"images/**/*.*",
		"source/**/*.*",
		"queries/*",
		"manifest",
		"lib/*",
		"!components/tests/**/*"
	],
	"bsConst": {
		"enable_http_logs": false,
		"ENABLE_RTA": false
	},
	"plugins": ["@rokucommunity/bslint"],
	"debug": {
		"enableDebugProtocol": true
	},
	"diagnosticFilters": [
		{ "src": "lib/**/*" },
		{ "src": "components/roku_modules/**/*" },
		{ "src": "source/roku_modules/**/*" }
	]
}
```
Reverting back to the previous release fixes this issue for me.

**Comment by bkdev98** [comment]
Same here 😅

**Comment by Allan-Nava** [comment]
Same problem here!

**Comment by alexlukhanin** [comment]
Same problem. Reverting back to 2.22.0 fixed this issue for me too.

**Comment by vinoth-discovery** [comment]
Same problem..

**Comment by koganiz** [comment]
Same here.

**Comment by mchoo-swm-qa** [comment]
Same here

**Comment by KennyOrellana** [comment]
Same here.
