### ISSUE TITLE
No BrightScript Log option in output

### ISSUE THREAD

**Issue by DusanLesan** [rokucommunity/vscode-brightscript-language#315]
Since the latest update 2.22.1, I have lost the option "BrightScript Log" in the output drop-down. Also, I have noticed other issues like error detection is not working, we cannot follow function calls with ctrl+click...
Previous version:
![pic-selected-210531-1240-42](https://user-images.githubusercontent.com/20520590/120183180-a694ce00-c20f-11eb-966e-84ef2461dfe9.png)
New version with same code:
![pic-selected-210531-1241-34](https://user-images.githubusercontent.com/20520590/120183299-cd530480-c20f-11eb-9412-b60e4cd51692.png)

**Comment by livecano** [comment]
I noticed this as well and also can't find a way to load .env variables into the launch.json since the latest update.

**Comment by TwitchBronBron** [comment]
This has been resovled in v2.22.2 and was caused by a missing prod dependency in roku-deploy
