### ISSUE TITLE
Makefile supported?

### ISSUE THREAD

**Issue by songhailiang** [rokucommunity/vscode-brightscript-language#323]
Hello,
Here I have a question about debugging. 
I'm using a Makefile with `make install` command to deploy the app to Roku device in my project.
Is this supported in this extension to debug?
Thanks.

**Comment by TwitchBronBron** [comment]
The extension needs to be in control of creating the zip and deploying it to the Roku. 

If your build process is simply zip creation and deployment, then you can use the files array in the vscode launch config to specify the list of files and you're good. 

If your make process is more involved, then you will need to customize your make process to place all your files into a staging directory and then point vscode's rootDir launch config parameter to that directory.

**Comment by TwitchBronBron** [comment]
Closing this since I believe the question has been answered.
