### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by khalilllk** [rokucommunity/vscode-brightscript-language#325]
- Issue Type: `Performance`
- Extension Name: `brightscript`
- Extension Version: `2.22.3`
- OS Version: `Windows_NT x64 10.0.18363`
- VS Code version: `1.58.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\ENG~1.KHA\AppData\Local\Temp\RokuCommunity.brightscript-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by TwitchBronBron** [comment]
@khalilllk we've made fairly significant changes to the extension logic since you posted this issue. I'm going to close this for now, but if you're still seeing issues, please comment and we can investigate.
