### ISSUE TITLE
Support preprogrammed keypresses

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/vscode-brightscript-language#327]
Add support for pre-programming keypresses to send to a roku device. Here is an example:
```js
  "brightscript.remoteSequences": {
      "viewTvGuide": [
          "pause:5ms",
          "ok",
          "text:bronley@gmail.com",
          "text:password",
          "down",
          "/tv shows highlighted/g",
          "ok",
          "sequence:goHome"
      ]
  },
  "brightscript.debug.activeRemoteSequences": ["viewTvGuide"]
```
Here are the features it should support:
- send roku remote presses ("ok", "left", "right", etc...).
- send text
- pause for a specified duration
- pause and monitor the output log until a regular expression match is found
- reference other remote sequences by name to reduce duplication

**Comment by chrisdp** [comment]
@TwitchBronBron we can resolve this as this has been added via RTA no?

**Comment by TwitchBronBron** [comment]
Hmm. Yeah, I think we _technically_ have implemented this. I like the idea of some of this stuff being in a config with a name. However, that's probably just a matter of adding some configuration options or import/export to the Roku Automation panel. So yeah, we can close this.
