### ISSUE TITLE
Add support for VS Code for the Web

### ISSUE THREAD

**Issue by luis-soares-sky** [rokucommunity/vscode-brightscript-language#332]
Github "recently" created github.dev (press `.` while viewing a project/PR) which uses the web version of VS Code. However, the BrightScript Language extension isn't supported at all.

![image](https://user-images.githubusercontent.com/57358121/139531723-899d99a0-7700-449e-9a4e-98b6bdca83ae.png)

So it would be great if the extension was (at least partially) supported by the web version of VSC, so that anyone could use github.dev to review PRs that contain .bs files.

**Comment by TwitchBronBron** [comment]
I'm definitely open to supporting this! There is a LOT of nodejs-specific code in the extension, so I'm not sure what all it would take to get the extension fully operational, but even if we could just get syntax highlighting working, that would be a great start.

**Comment by TwitchBronBron** [comment]
FYI, I'm reading the docs about this. I'll try to play around with a basic implementation in the next week or so. Colorization should be very simple.

**Comment by TwitchBronBron** [comment]
@luis-soares-sky I just submitted #333 which adds the minimal required info to get the extension to launch in the browser. Almost none of the features will work right now, as we need to refactor the build process to bundle for web.

**Comment by TwitchBronBron** [comment]
@luis-soares-sky did you have a chance to test it out yet? Are there additional features you'd like to see sooner rather than later?

**Comment by luis-soares-sky** [comment]
I believe the immediate requirement from our team was mainly syntax highlighting, as that's mostly what we use the web version for. Some of us have tested it and it seems to be running smoothly!
