### ISSUE TITLE
Registry information wiped on deploy

### ISSUE THREAD

**Issue by lumpenprole** [rokucommunity/vscode-brightscript-language#337]
The latest update seems to wipe all registry information on deploy causing me to have to log in to the application I'm developing each time I deploy. I'm currently trying to deploy with vanilla roku-deploy to see if that is the issue, but it's taking some work.

**Comment by chrisdp** [comment]
Hey @lumpenprole we found the issue a couple days ago. It was due to a small change we made that deleted the channel before side loading. If your device was not rekeyed to the same key as one of your installed applications it would cause this issue. An update should be coming out soon to fix this.

**Comment by lumpenprole** [comment]
Fantastic! Thank you!

**Comment by TwitchBronBron** [comment]
This is fixed in the latest release (v2.24.1). Sorry for the delay getting this out.

**Comment by lumpenprole** [comment]
Thanks for the prompt action!
