### ISSUE TITLE
Add flag to disable "Deleting sideloaded channel" during debug start

### ISSUE THREAD

**Issue by luis-soares-sky** [rokucommunity/vscode-brightscript-language#338]
As of Roku OS 10.5, the registry appears to be cleared every time the sideloaded app is explicitly deleted (`mysubmit=Delete`) before installing. Due to this, we are forced to login on every launch of our app via VSC, because the extension runs `Deleting existing sideloaded channel (if there is one)`.

Is it possible to add a setting that allows us to disable this behaviour?

**Comment by TwitchBronBron** [comment]
We actually just fixed this issue.. See https://github.com/rokucommunity/vscode-brightscript-language/issues/337
