### ISSUE TITLE
If and If Else snippets to include then

### ISSUE THREAD

**Issue by DusanLesan** [rokucommunity/vscode-brightscript-language#347]
I have seen that in most places adding `then` keyword in every `if` and `else if` is a standard. Could you update your snippets in vscode-brightscript-language/snippets/brightscript.json to include `then` keyword? 
Furthermore, If Else snippet should have a third jumping point after else.

Something like:

```
    "If": {
        "prefix": "if",
        "body": [
            "if ${1:condition} then",
            "\t$0",
            "end if"
        ],
        "description": "Simple if statement"
    },
    "If Else": {
        "prefix": "if-else",
        "body": [
            "if ${1:condition} then",
            "\t$2",
            "else",
            "\t$0",
            "end if"
        ],
        "description": "Simple if/else statement"
    },
```

**Comment by chrisdp** [comment]
I wouldn't consider the `then` statement as standard. It's an optional key word and really comes down to individual coding standards.

**Comment by DusanLesan** [comment]
@chrisdp You may be right. Is it possible then to make this part dynamic and set it based on user preference?

**Comment by chrisdp** [comment]
@TwitchBronBron would know more about if it could or could not be set dynamically. 

As for a setting we would have to think how because this falls more in the territory of a linter like BSLint.

**Comment by DusanLesan** [comment]
Other possibility would be to override the snippet directory in brightscript plugin for vs code.

**Comment by TwitchBronBron** [comment]
Snippets are defined statically in the extension's package.json so I don't think we can dynamically set these. 

However, if you'd like, we can add another differently-named snippet which includes the `then`? The current trigger for an if statement without `then` is `if`. How about we add `ift` which would include the `then`?

**Current:**
| Trigger word | Snippet |
| ------------- | ------------- |
| `if`  | if ${1:condition} <br/>&nbsp;&nbsp;&nbsp;&nbsp;$0<br/>end if|
| `if-else`  | if ${1:condition}<br/>&nbsp;&nbsp;&nbsp;&nbsp;$0<br/>else<br/>&nbsp;&nbsp;&nbsp;&nbsp;<br/>end if|

**Proposed additions:**
| Trigger word | Snippet |
| ------------- | ------------- |
| `ift`  | if ${1:condition} then <br/>&nbsp;&nbsp;&nbsp;&nbsp;$0<br/>end if|
| `ift-else`  | if ${1:condition} then<br/>&nbsp;&nbsp;&nbsp;&nbsp;$0<br/>else<br/>&nbsp;&nbsp;&nbsp;&nbsp;<br/>end if|

**Comment by DusanLesan** [comment]
I do not like that as much as setting my own path to my snippets.json in plugin settings.

**Comment by TwitchBronBron** [comment]
vscode requires that all extension-contributed snippets be defined in the package.json of the extension, and vscode does not allow us to reassign them at runtime. 

You can add your own snippets in vscode directly without the need for any support from our extension. 

![Animation](https://user-images.githubusercontent.com/2544493/148404547-9d2abeac-3dd3-4ebf-8016-632eb3816310.gif)

**Comment by DusanLesan** [comment]
@TwitchBronBron That is what I need. It is bad experience to have duplicates I do not want but that is the same as if you add ift/ift-else. Thank you for the help and information

**Comment by TwitchBronBron** [comment]
You can hide unwanted snippets as well:
![Animation](https://user-images.githubusercontent.com/2544493/148406924-1d38f3c9-e56b-40c8-9f0a-abd7716deb7e.gif)

**Comment by DusanLesan** [comment]
Awesome. All is great now
