### ISSUE TITLE
debugger can cause crashes on tasks waiting on messages

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/vscode-brightscript-language#35]
I find when debugging tasks that code like this can cause crashes:
```	while(true)
		msg = wait(0, m.port)

		msgType = type(msg)
		if msg <> invalid and msgType = "roSGScreenEvent"
			if msg.isScreenClosed() then return
    else msgType = "roSGNodeEvent"
      if msg.getField() = "closeChannel" then return
		end if
	end while```

msg ends up being invalid, despite putting guards in various places

**Comment by TwitchBronBron** [comment]
When you say crashes, what do you mean? Does the extension stop debugging? Does it just get stuck?

**Comment by georgejecook** [comment]
Causes app to crash.

I get this sometimes debugging without the plugin; but it seems to happen
more with the plugin.

I'll submit a video.

**Comment by chrisdp** [comment]
@georgejecook I assume this issue is really a problem anymore? Can we close this issue?
