### ISSUE TITLE
Better settings organization

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/vscode-brightscript-language#378]
vscode has a nice user interface for settings. You can include categories that help group the settings visually. Like this:
![image](https://user-images.githubusercontent.com/2544493/162749830-6595358f-3b5d-4edb-8e99-ef420180a921.png)

We should do the same thing for our various settings. Categories like `Formatting`, `Debugging`, etc...

See [this gitlense package.json](https://github.com/gitkraken/vscode-gitlens/blob/26e69fc31d1d9e6cd5125becc2f8c7cdedce628b/package.json#L221) for how to achieve this.

Here's the first bit from our code:
![image](https://user-images.githubusercontent.com/2544493/162750157-519a525d-9229-4447-9d68-c4dc5a3b382e.png)

**Comment by philanderson888** [comment]
First contribution to roku brightscript open source

Pull request https://github.com/rokucommunity/vscode-brightscript-language/pull/390 created and awaiting feedback.

**Comment by TwitchBronBron** [comment]
This was implemented in #390
