### ISSUE TITLE
roInteger and roIntrinsicDouble not colored

### ISSUE THREAD

**Issue by chrisdp** [rokucommunity/vscode-brightscript-language#394]
![image](https://user-images.githubusercontent.com/9591618/169047500-c199f86f-7fea-4d3f-969e-3754a4e4a2ae.png)
![image](https://user-images.githubusercontent.com/9591618/169047690-ed444998-832f-4ec2-9c2a-241b11123f73.png)

**Comment by TwitchBronBron** [comment]
roInteger is not a valid component.

```
print CreateObject("roInteger")
```

```
BRIGHTSCRIPT: ERROR: Runtime: unknown classname "roInteger": pkg:/source/main.brs(4)
```

However, roIntrinsicDouble _is_ valid, so we should fix that one.
