### ISSUE TITLE
Add all launch.json options into user settings under `brightscript.debug`

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/vscode-brightscript-language#399]
The debugger currently supports adding any launch.json setting to user settings under `brightscript.debug`. However, almost none of those options are documented, so they show up as "unknown value". 

1. Copy (duplicate, don't move) all of the launch.json options into user settings. The naming convention should be `brightscript.debug.<name launch config value>` . 

This will result in a _lot_ of duplication, but will provide a much nicer user experience. If you're feeling creative, you could write a nodejs (typescript) script to auto-sync all the launch.json settings into the package.json user settings instead of copying them by hand.

**Comment by philanderson888** [comment]
Code is now complete and submitted for pull request

**Comment by philanderson888** [comment]
https://github.com/rokucommunity/vscode-brightscript-language/pull/438

**Comment by philanderson888** [comment]
Now I have the code functioning correctly there is one final thing - I remember I have to now add the linting tests, which are not currently running ...

**Comment by philanderson888** [comment]
OK modified file to add in fixes for ESLinting errors highlighted

**Comment by TwitchBronBron** [comment]
Fixed by #438
