### ISSUE TITLE
Enums not colored correctly in if statment

### ISSUE THREAD

**Issue by chrisdp** [rokucommunity/vscode-brightscript-language#402]
![image](https://user-images.githubusercontent.com/9591618/171736355-cb43f21d-3431-49d8-991e-88c62fe9f168.png)

```vb
' Validate the priority of the request
priority = Get.String([[request, "parameters.priority"]], RequestPriority.DEFAULT)
if priority <> RequestPriority.LOW and priority <> RequestPriority.MEDIUM and priority <> RequestPriority.HIGH then priority = RequestPriority.DEFAULT
```

```vb
enum RequestPriority
	LOW = "low"
	MEDIUM = "medium"
	HIGH = "high"
	DEFAULT = "medium"
end enum
```

**Comment by chrisdp** [comment]
@TwitchBronBron did we end up fixing this issue? Feel like we _might_ have. But I also could be wrong.

**Comment by TwitchBronBron** [comment]
Yes, it appears we've fixed this issue. Not sure when. 

![Image](https://github.com/user-attachments/assets/72a60d79-c2ff-4b51-ba4e-e0f491f37f29)
