### ISSUE TITLE
feature request: extends brightscript.tmLanguage.json to support .bs

### ISSUE THREAD

**Issue by ZeeD** [rokucommunity/vscode-brightscript-language#424]
The project offers a tm grammar. But from looking at

https://github.com/rokucommunity/vscode-brightscript-language/blob/159fd098918d62a25591b4e55ea228c5ff40f0ab/syntaxes/brightscript.tmLanguage.json#L4-L6

it seems it's only for ".brs" (BrightScript) files. It would be possible to add ".bs" (BrighterScript) files to it? does it already cover both languages?

**Comment by TwitchBronBron** [comment]
Yeah, it covers both .brs (BrightScript) and .bs (BrighterScript). I didn't see the benefit to maintaining two completely separate grammars that were 98% the same, especially considering we have a langauge server that would provide diagnostics when using .bs features inside a .brs file. You can see them both referencing the same grammar file [here](https://github.com/rokucommunity/vscode-brightscript-language/blob/159fd098918d62a25591b4e55ea228c5ff40f0ab/package.json#L718-L729).

**Comment by ZeeD** [comment]
cool!
can I suggest to change the .json to add `"bs"` to `"fileTypes"` then? [tm4e](https://projects.eclipse.org/projects/technology.tm4e) it's a bit finicky and relies on that field to know on what extensions add syntax highlight

**Comment by TwitchBronBron** [comment]
Sure! Go ahead and open a PR for that.

**Comment by ZeeD** [comment]
opened #425
