### ISSUE TITLE
Roca Test scripts are marked as not being referenced

### ISSUE THREAD

**Issue by xgouchet** [rokucommunity/vscode-brightscript-language#428]
I'm using [Roca](https://github.com/hulu/roca) to write and run unit tests in my projects. Test files live in a `tests` folder, and by definition they are not referenced in either the `source` or `components` folders, meaning that all my test files have a warning: 

> This file is not being referenced by any other file in the project.

Could we disable the reference check for the `tests` folder?

**Comment by TwitchBronBron** [comment]
You can disable that warning yourself by creating a `bsconfig.json` at the root of your vscode workspace, and then adding this content:
```jsonc
{
    "diagnosticFilters": [{
        "src": "tests/**/*",
        "codes": [1013]
    ]]
}
```

**Comment by xgouchet** [comment]
Thanks didn't know that. Is there a documentation on all the diagnostic filters and which code they have?

**Comment by TwitchBronBron** [comment]
The list of codes that brighterscript includes is found in [this file](https://github.com/rokucommunity/brighterscript/blob/master/src/DiagnosticMessages.ts), but each bsc plugin can have its own list of filters as well.

There's also [this small section](https://github.com/rokucommunity/brighterscript#bsconfigjson-options) in the brighterscript readme showing how to use `diagnosticFilters`.   
![image](https://user-images.githubusercontent.com/2544493/185910698-5ced8410-6884-417e-9e70-4b618b0f8972.png)
