### ISSUE TITLE
debugger can become inoperational when changing ip address on roku

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/vscode-brightscript-language#43]
if I change my roku's network (I do this a lot due to VPN), the telnet connection get's gummed up and I need to restart the vscode plugin AND my roku box.

Not sure if this is a roku issue; didn't test against eclipse/telnet for example.

**Comment by chrisdp** [comment]
@georgejecook is this still an issue for you. I run my VPN on my router so turning it on and off hasn’t affected me more have I seen this issue.

**Comment by georgejecook** [comment]
fixed.
