### ISSUE TITLE
Wrong highlighting if the last symbol in the string is a backslash

### ISSUE THREAD

**Issue by vbuchii** [rokucommunity/vscode-brightscript-language#441]
It seems like the presence of a backslash in the string escapes the next character. And due to that all the following code is not properly highlighted:

![Screenshot from 2022-10-20 21-35-22](https://user-images.githubusercontent.com/26671643/197030928-7b069933-3bc2-48af-aa12-28846bef21d9.png)

**Comment by TwitchBronBron** [comment]
Hmm. I just tried to reproduce this, and it appears to be working fine for me. What version of vscode and the brightscript extension are you using? Notice how in your example, there are several other items that aren't colored correctly (such as `someFunc` being white instead of yellow, `data` is white instead of light blue, etc). Is htere something above your code that's causing the rest of the file to be parsed incorrectly?

![image](https://user-images.githubusercontent.com/2544493/197041655-a4e5a43b-b72e-44cf-82fd-6dfd7be1d774.png)

**Comment by vbuchii** [comment]
@TwitchBronBron, thank you for the quick response. Just tried in an empty file and it looks the same for me. 

**VS Code:** 
```
Version: 1.72.2
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:16:26.920Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.14.0-1052-oem
Sandboxed: No
```
**BrightScript Language extention:**
![Screenshot from 2022-10-21 08-52-53](https://user-images.githubusercontent.com/26671643/197122717-e75d1152-5896-4ee9-8296-b6c229e8d05f.png)

**Comment by TwitchBronBron** [comment]
Hmm. can you try uninstalling the extension and then re-installing the extension, and then restarting all of your vscode windows? I'd love to fix this if I can find a way to reproduce it. :)

**Comment by vbuchii** [comment]
> Hmm. can you try uninstalling the extension and then re-installing the extension, and then restarting all of your vscode windows? I'd love to fix this if I can find a way to reproduce it. :)

Already did that a while ago and just tried to do it again, but unfortunately, it doesn't help. Anyway, thank you for trying to help :)

**Comment by TwitchBronBron** [comment]
If you've got some time, I'd love to help troubleshoot this. Could you send me a message in our [RokuCommunity slack](https://join.slack.com/t/rokudevelopers/shared_invite/zt-4vw7rg6v-NH46oY7hTktpRIBM_zGvwA)? We can set up a video screen share and I can see what's going on.

**Comment by vbuchii** [comment]
> If you've got some time, I'd love to help troubleshoot this. Could you send me a message in our [RokuCommunity slack](https://join.slack.com/t/rokudevelopers/shared_invite/zt-4vw7rg6v-NH46oY7hTktpRIBM_zGvwA)? We can set up a video screen share and I can see what's going on.

Thanks @TwitchBronBron 
I wrote you in private.

**Comment by TwitchBronBron** [comment]
This issue was caused by having the `vscode-ide-brightscript` extension installed alongside this one.

**Comment by vbuchii** [comment]
> This issue was caused by having WillowTree's `vscode-ide-brightscript` extension installed alongside this one. Uninstalling `vscode-ide-brightscript` fixed the issue.

Thanks again for your help! I appreciate it.
