### ISSUE TITLE
v2.38.1 Can't get this extension to work

### ISSUE THREAD

**Issue by roidy** [rokucommunity/vscode-brightscript-language#447]
I'm trying to learn Roku development but this extension is driving me crazy. I've downloaded the hello-world example from https://github.com/rokudev/hello-world

Opened it in VSCode and created a launch.json in the root directory:-

```
{
    "version": "0.2.0",
    "configurations": [
      {
        "type": "brightscript",
        "request": "launch",
        "name": "BrightScript Debug: Launch",
        "host": "192.168.0.30",
        "password": "*******",
        "rootDir": "${workspaceFolder}"
      }
    ]
  }
```

But every time I try to run and debug Main.brs I get the following error:-

`Cannot zip package: missing manifest file in "d:\hello-world-master\out\.roku-deploy-staging"`

Help please.

VSCode 1.70.2
Brightscript Language v2.38.1
Tried under Windows 11, OSX 12 and OSX 13

**Comment by TwitchBronBron** [comment]
2 things:

1. Make change rootDir to this because it needs to point to the folder containing the manifest file. 
```
"rootDir": "${workspaceFolder}/source"

2. Make sure the launch.json is inside the .vscode folder at the root of your workspace.

**Comment by roidy** [comment]
>"rootDir": "${workspaceFolder}/source"

Perfect, that did it. Thank you very much for the very fast support 👍

**Comment by TwitchBronBron** [comment]
You're welcome! Glad that did the trick. :)
