### ISSUE TITLE
support enable/disable breakpoints

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/vscode-brightscript-language#46]
It should be possible to inject code into an app such that we can create a `global._vsCodeIdeBreakpoints` map, which contains true/false states for all breakpoints. We can then, instead of injecting STOP into the code, inject something long the lines of 
`if m.global._vsCodeIdeBreakpoints[breakpointId] = true then stop`

We will need an expanded guard, because global might not be available in some circumstances; but I think we could get a pretty general system that works in a majority of cases.

This will give developers the ability to enable/disable breakpoints at run-time. Of course, this would not facilitate dynamic breakpoints; but I can still think of many use cases where such a system is tremendously useful.

**Comment by TwitchBronBron** [comment]
VSCode alerts the extension anytime a breakpoint is added, removed, or disabled in the source code. As such, the extension already detects when a STOP statement is hit, and could easily decide whether to actually break or just continue for disabled/removed breakpoints. 

What's the advantage of your approach over what I mentioned above?

**Comment by georgejecook** [comment]
1. Stopping is slow as hell - especially in an SGNode. So stopping and auto
continue using would just mean the app hangs. In even a moderately right
loop it would be untenable.

2. in many cases continue crashes the aop. There's an existing issue which
prevents rokus from recovering from a stop - all wait loops in the tasks
and main progressively fail with invalid or incorrect event message data. I
thought I'd raised this issue already. I've mentioned it in slack and
others have verified the issue. If it's not already raised I'll raise it.

**Comment by georgejecook** [comment]
@TwitchBronBron can you assign this to me, please? I can't live without it anymore.

My suggested solution is each breakpoint has a unique id associated with it, and that instead of STOP we put a line of code which can check with a mechanism available on m.global - and if m.global is not avaiable, revert to stop

so we can insert:
`if m.global <> invalid and m.global._vsl_breakpoints <> invalid and m.global._vsl_breakpoints.breakpointId = true then stop

We can add this with a feature flag, so that it can be turned on off/so developers who use it understand that they need `m.global` to be available for the toggle behavior of the breakpoint.

Further to this, we will need a socket connection, so that we can update m.global._vsl_breakpoints in accordance with vscode breakpoint toggles.

**Comment by TwitchBronBron** [comment]
I was actually thinking about this today, and had a slightly different thought. 

We could add your proposed line to EVERY line of runnable code in the entire project instead of just the marked breakpoint lines. 

Then, when we launch the debugger, we would also pass along the "which breakpoint lines are enabled"  statement too. 

The benefit to my approach is that would allow us to add new breakpoints after launch. 

Thoughts?

**Comment by TwitchBronBron** [comment]
Also, if we modify your line to always call the stop statement if m.global is not available, we don't have to hide it behind a flag because the functionality hasn't changed 

Something like 

`If m.global = invalid or m.global.vbl_enabled_breakpoints[1]  <> invalid then stop`

**Comment by TwitchBronBron** [comment]
The socket part....we already have a connection established in the rokuAdapter for all other debugger commands. So the flow would be

1. Issue a pause command
2. Send an evaluate command to enable/disable the breakpoint `m.global.vbl_enabled_breakpoints.bp1 = true` or `m.global.vbl_enabled_breakpoints.delete("bp1")`
3. Send a resume command 

We might need to select the proper thread between 2 and 3...but we can tackle that as we get to it.

**Comment by georgejecook** [comment]
Hahaha. I thought of that. But I thought it'd be beyond crazy in terms of
performance and mappings.

Perhaps you're smarter than I but I had no idea how you can toggle a
condition on an if statement or for or while etc etc.

 Can try a spike out on 2 large projects if you just want to try a build
that adds the stop guards to see how it performs..

**Comment by TwitchBronBron** [comment]
I can't imagine it having any noticeable performance impact....these statements are not heavy. 

For now, you can go ahead and just add the stop guards for the known breakpoints, and we can expand on that later. 

Ping me if you need any help.

**Comment by TwitchBronBron** [comment]
So the pause/resume im talking about is done over telnet, it's when you type ctrl+c and it pauses execution. is that the same pause that takes 20 seconds for you? If so, then how is debugging even ever working using this extension at all?

**Comment by TwitchBronBron** [comment]
I just tested on a Roku 2 XD: 

1. Open a telnet session using Putty
2. Launch a sideloaded app using the roku remote
3. In the telnet session, press ctrl+c which enters into the roku debug prompt

It took less than a second for the `ctrl+c` command to execute. Every part of the current debugger implementation in this extension depends on using that debug terminal. It sends lots of commands to get things like threads, variables, watches, etc. Then when you press continue, it resumes execution until the next "stop" breakpoint. 

I'm not seeing near the performance hit that you are, and it's running on like 7 year old hardware. Are we talking about the same thing?

**Comment by TwitchBronBron** [comment]
It was a simple app, with no background tasks. :D 

I would recommend the first iteration of this ticket be to switch from `stop` commands to the conditional statements, with my above steps for enabling/disabling the breakpoints whenever a user enables/disables/deletes breakpoints after debugging has started. That would validate that it works, without all the added work of integrating sockets into the mix. We can always improve upon this in the future as we get time. 

But your call how you want to tackle it. I'm open to the socket thing as long as that will solve the problem and not crash apps that would otherwise work.

**Comment by georgejecook** [comment]
Agree. I'll send Roku more details. Hopefully they can fix the issue and
this solution will be good to go formbigger projects.

On Jan 12, 2019 11:41 PM, "Bronley Plumb" <notifications@github.com> wrote:

It was a simple app, with no background tasks. :D

I would recommend the first iteration of this ticket be to switch from stop
commands to the conditional statements, with my above steps for
enabling/disabling the breakpoints whenever a user enables/disables/deletes
breakpoints after debugging has started. That would validate that it works,
without all the added work of integrating sockets into the mix. We can
always improve upon this in the future as we get time.

But your call how you want to tackle it. I'm open to the socket thing as
long as that will solve the problem and not crash apps that would otherwise
work.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/TwitchBronBron/vscode-brightscript-language/issues/46#issuecomment-453801729>,
or mute the thread

**Comment by chrisdp** [comment]
Thinking with the work happening on the debug protocol we can likely close this issue @georgejecook @TwitchBronBron ?

**Comment by georgejecook** [comment]
yep.
