### ISSUE TITLE
bsConst in launch.json does not affect component libraries

### ISSUE THREAD

**Issue by iBicha** [rokucommunity/vscode-brightscript-language#461]
bsConst are being updated on the app manifest, but not component libraries

**Comment by TwitchBronBron** [comment]
Hmm. Component libraries and the main project all flow through the same manifest transformation  logic here: https://github.com/rokucommunity/roku-debug/blob/bb2146888261a7d2d21cdb17dc31e1715e72ae2a/src/managers/ProjectManager.ts#L291

Are you using a preprocessor or brighterscript somewhere by chance? Because brighterscript currently transpiled away all the false blocks. (We want to fix that eventually...)

**Comment by iBicha** [comment]
> Hmm. Component libraries and the main project all flow through the same manifest transformation logic here: https://github.com/rokucommunity/roku-debug/blob/bb2146888261a7d2d21cdb17dc31e1715e72ae2a/src/managers/ProjectManager.ts#L291
> 
> Are you using a preprocessor or brighterscript somewhere by chance? Because brighterscript currently transpiled away all the false blocks. (We want to fix that eventually...)

I'm using brighterscript, and the output of it contains all the false values.

Like after transpiling with bsc my manifest still has
```
bs_const=DEBUG=false;WEB_SERVER_BASIC_AUTH=false;DASH_THUMBNAILS=false;WEB_SOCKETS=true
```

**Comment by iBicha** [comment]
Also, I don't see it looping through all manifests, or is a [Project](https://github.com/rokucommunity/roku-debug/blob/bb2146888261a7d2d21cdb17dc31e1715e72ae2a/src/managers/ProjectManager.ts#L224) object created for each component library?

**Comment by TwitchBronBron** [comment]
I wasn't talking about the manifest itself, i was talking about the code. So Something like this:

bs_const=some_true_value=true;some_false_value=false;

```
#if some_true_value
    'i get to stay
#end if
#if some_false_value
    'i get deleted
#end if 
```

will result in this output code:
```
#if some_true_value
    'i get to stay
#end if 
```

**Comment by iBicha** [comment]
Got it, sorry for not being clear. No what's missing is the manifest of the component library is not updated according to the launch config

**Comment by TwitchBronBron** [comment]
> Got it, sorry for not being clear. No what's missing is the manifest of the component library is not updated according to the launch config

Ah, ok. Well then yeah, I guess there's a bug somewhere. Maybe vscode isn't sending the bsconst stuff up for complibs during launch. 

> Also, I don't see it looping through all manifests, or is a Project object created for each component library?

Yeah, we make one project for the main app, and a project for each complib.

**Comment by iBicha** [comment]
To work around the issue, I was trying to modify the manifest in staging just before bsc starts transpiling.
[Turns out bsc does not care about the manifest in the staging](https://github.com/rokucommunity/brighterscript/blob/dc15156603f97513063df5e6f09a5e16ac443246/src/Program.ts#L1367).

I ended up modifying the actual rootDir manifest right before bsc does work, and restoring it back later ([plugin](https://github.com/iBicha/playlet/blob/1faec073f0be6f26d3049c1bc78269b126aebf8c/tools/manifest-bsconst-debug-plugin.ts))

**Comment by TwitchBronBron** [comment]
BrighterScript v1 recently introduced proper AST support for conditional compile statements being transpiled into the output (see https://github.com/rokucommunity/brighterscript/pull/1149). So I'm going to close this issue, as it should eventually be fixed with v1 lands.
