### ISSUE TITLE
Crash when opening Roku Registry

### ISSUE THREAD

**Issue by zeronil** [rokucommunity/vscode-brightscript-language#468]
There appears to be a bug in the newer builds of the extension. When the "Roku Registry" is opened a crash occurs that seems to be caused because the function "logDebug" is not defined. I can roll back to version 2.38.3 and the crash does not occur, but newer builds seem to have this issue.

Suspending threads...
Thread selected:  8*   ...RTA_OnDeviceComponentTask.brs(446)   logDebug("Sending back large response (id: " + json.id + ", 
Current Function:
438:    if response.id = Invalid then
439:        response.id = json.id
440:    end if
441:  
442:    stringPayload = formatJson(response)
443:    if stringPayload.len() < 1024 then
444:        logDebug("Sending back response for requestType: " + json.type, stringPayload)
445:    else
446:*       logDebug("Sending back large response (id: " + json.id + ", requestType: " + json.type + ", success: " + response.success.toStr() + ", timeTaken: " + response.timeTaken.toStr() + ")")
447:    end if
448:  
449:    ba = createObject("roByteArray")
450:    ba[m.requestHeaderSize - 1] = 0
Source Digest(s): 
pkg:               dev    9.4.0 d25e86fe Spectrum TV 9.4.0(20230306)
roku_analytics: 109022    1.4.7 533c3ca6 Roku Analytics Library
roku_ads_lib:    58484   3.3.27 96f8759e Roku Ads Library
pkg:            632051 1.0.1272 944bd7d4 libwidevine
pkg:            632126    1.0.1 4753b501 libplayready
Interface not a member of BrightScript Component (runtime error &hf3) in pkg:/components/RTA_OnDeviceComponentTask.brs(446)
Backtrace:
#5  Function sendresponsetoclient(request As Object, response As Object) As Dynamic
   file/line: pkg:/components/RTA_OnDeviceComponentTask.brs(446)
#4  Function processreadregistryrequest(request As Object) As Void
   file/line: pkg:/components/RTA_OnDeviceComponentTask.brs(270)
#3  Function verifyandhandlerequest(request As Dynamic) As Void
   file/line: pkg:/components/RTA_OnDeviceComponentTask.brs(231)
#2  Function handleclientsocketevent(messagesocketid As String, clientsocket As Object, bufferlength As Integer) As Void
   file/line: pkg:/components/RTA_OnDeviceComponentTask.brs(135)
#1  Function handlesocketevent(message As Object) As Void
   file/line: pkg:/components/RTA_OnDeviceComponentTask.brs(102)
#0  Function runtaskthread() As Void
   file/line: pkg:/components/RTA_OnDeviceComponentTask.brs(73)
Local Variables:
request          roAssociativeArray refcnt=4 count:6
response         roAssociativeArray refcnt=1 count:3
binarypayloadbytearray Invalid
global           Interface:ifGlobal
m                roAssociativeArray refcnt=7 count:11
json             roAssociativeArray refcnt=3 count:4
stringpayload    roString (2.1 was String) refcnt=1 val:"{"id":"hesssEQ","success":true,"values":{"Default":{"cdvrDeviceId":"c21b0df2-d9f2-57d7-b243-2d"...
ba               <uninitialized>
stringpayloadbytearray <uninitialized>
socket           <uninitialized>
bytesremaining   <uninitialized>
currentindex     <uninitialized>
bytessent        <uninitialized>
Threads:
ID    Location                                Source Code
 0    pkg:/source/Main.brs(320)               message = wait(0, m.port)
 1    ...antGuideProgressIndicator.brs(57)    Sub onTimeChangeTimerFired(event as Object)
 2    ...s/tasks/venona/VenonaTask.brs(559)   message = m.port.WaitMessage(0)
 3    ...ToSpeech/TextToSpeechTask.brs(63)    message = wait(0, m.port)
 4    ...r/NetworkTransfer_GetTask.brs(112)   event = wait(m.timeout, m.messagePort)
 5    .../NetworkTransfer_PostTask.brs(117)   msg = wait(m.timeout, m.messagePort)
 6    ...sks/registry/RegistryTask.brs(56)    message = wait(0, m.port)
 7    ...ts/tasks/rmf/RmfEventTask.brs(54)    message = wait(0, m.port)
 8*   ...RTA_OnDeviceComponentTask.brs(446)   logDebug("Sending back large response (id: " + json.id + ", 
 9    .../components/AnalyticsNode.brs(136)   ??
10    ...tion/tdcs/TDCSRefreshTask.brs(55)    message = wait(0, m.port)
11    ...s/WebSocket/WebSocketTask.brs(427)   event = wait(0, m.port)
12    .../tasks/EAS/EASControlTask.brs(70)    event = wait(1000, m.port)
13    ...mServer/ProgramServerTask.brs(165)   message = wait(0, m.port)
14    ...s/tasks/portal/PortalTask.brs(319)   event = wait(0, m.port)
15    .../NNSEntryPointRefreshTask.brs(86)    message = wait(0, m.port)
16    ...ntGuide/GuideProgramsTask.brs(163)   msg = wait(0, m.port)
  *selected

**Comment by TwitchBronBron** [comment]
@zeronil we've released a few updates to this section of the project since you opened this issue. Can you try the latest version of the extension and see if this issue is still occurring?

**Comment by zeronil** [comment]
I have version 2.39.0 installed and it doesn't crash, but as soon as I select "Roku Registry" the Debug Console is flooded with the following message (it continues until I exit the running app):

04-17 14:36:59.676 [RTA][ERROR] Received message did not contain valid request 
BRIGHTSCRIPT: ERROR: ParseJSON: Data is empty: pkg:/components/RTA_OnDeviceComponentTask.brs(216)
04-17 14:36:59.685 [RTA][ERROR] Received message did not contain valid request 
BRIGHTSCRIPT: ERROR: ParseJSON: Data is empty: pkg:/components/RTA_OnDeviceComponentTask.brs(216)
04-17 14:36:59.694 [RTA][ERROR] Received message did not contain valid request 
BRIGHTSCRIPT: ERROR: ParseJSON: Data is empty: pkg:/components/RTA_OnDeviceComponentTask.brs(216)

**Comment by triwav** [comment]
@zeronil do you mind going into your launch.json and adding `"logLevel": "debug"` to your active configuration and either posting the information here or DM me @bleighty in the Roku Slack
