### ISSUE TITLE
VSC shutdown causes endless "home" keypresses

### ISSUE THREAD

**Issue by luis-soares-sky** [rokucommunity/vscode-brightscript-language#481]
Using macOS Ventura 13.3.1, VSC 1.78.0.

I got a weird one ever since upgrading the extension from 2.40.0 to 2.40.1: when I exit VSC after at least one debug session, the device I used (usually a Roku Ultra 4670X, connected via WiFi) will start getting spammed with constant "home" keypresses.

I could not identify the root cause as every code process is killed properly, and the only workaround I found so far is to reboot the laptop. If I unplug the Roku and plug it back in without rebooting the laptop, it'll eventually start getting spammed again.

I've since rolled back the extension version to 2.40.0, and the problem is gone.

**Comment by TwitchBronBron** [comment]
That's probably the weirdest bug I've ever seen. I have no idea why it would be doing this! We only send a home press ONCE at the start of the debug session.

**Comment by luis-soares-sky** [comment]
It is one of the weirdest things I've seen as well. Not sure if you were able to repro it, but here's a quick video showing what happens.

https://github.com/rokucommunity/vscode-brightscript-language/assets/57358121/2842c2e4-fc50-4c2f-b2f9-602bcf180220

**Comment by TwitchBronBron** [comment]
Is this still happening? I haven't been able to reproduce it yet.

**Comment by luis-soares-sky** [comment]
Yep, still happens with 2.40.1.

**Comment by TwitchBronBron** [comment]
I believe this is caused by https://github.com/rokucommunity/roku-debug/pull/152 , where the .shutdown() function enters an infinite loop, where one of the steps is to send a home press.

**Comment by luis-soares-sky** [comment]
Fixed in 2.40.4. Thank you!
