### ISSUE TITLE
fix syntax highlighting in interface comments

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/vscode-brightscript-language#488]
![image](https://github.com/rokucommunity/vscode-brightscript-language/assets/2544493/0554808d-c39f-4302-b252-5815ed75e5c6)

**Comment by chrisdp** [comment]
Looks like this has been fixed in resent updates:
![Image](https://github.com/user-attachments/assets/7cab5b05-0d51-4737-bc0f-609f12440a9a)

**Comment by TwitchBronBron** [comment]
Yeah, this was fixed in https://github.com/rokucommunity/vscode-brightscript-language/pull/489
