### ISSUE TITLE
Use SSDP for device discovery

### ISSUE THREAD

**Issue by unwiredben** [rokucommunity/vscode-brightscript-language#501]
It uses less resources on the Roku devices to discover them using SSDP as opposed to trying a ECP connection, as SSDP uses a single multicast query that covers the whole network at once.  See https://developer.roku.com/docs/developer-program/dev-tools/external-control-api.md#simple-service-discovery-protocol-ssdp for details.

**Comment by chrisdp** [comment]
Hey @unwiredben we do use SSDP for device discovery. Is there something in particular you could see us changing about how we do this?

**Comment by unwiredben** [comment]
ah, this came from an internal conversation, I didn't realize it was already in use.  I think what ends up happening is SSDP identifies devices, but that's then followed by a ECP probe to get device info.

**Comment by unwiredben** [comment]
this can be closed
