### ISSUE TITLE
Add support for surrounding text with backticks in .bs files

### ISSUE THREAD

**Issue by cewert** [rokucommunity/vscode-brightscript-language#526]
I started using template literals recently and when you highlight text in a `.bs` file and then hit the backtick button, the text is erased and replaced with a backtick instead of being surrounded with backticks like when working with a javascript file in vscode. I would like to add this functionality to `.bs` files.

**Comment by TwitchBronBron** [comment]
I think they just need to be added to these:

https://github.com/rokucommunity/vscode-brightscript-language/blob/c7d9f7b056df25d7f68b16b817a130cd756e906d/language-configuration.json#L19
