### ISSUE TITLE
Need test launch config support

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/vscode-brightscript-language#53]
Would be great to have additional launch configs for test, which will pass in the requisite launch params to activate the unit testing framework (such as: [https://github.com/georgejecook/rooibos/blob/master/docs/index.md#configuring-rooibos](https://github.com/georgejecook/rooibos/blob/master/docs/index.md#configuring-rooibos) - note rooibos has the same runtime setup as the official Roku Unit testing framework).

**Comment by TwitchBronBron** [comment]
If I understand you correctly, then this is already supported natively in VSCode. The `name` field of a launch.json config lets you give a unique name to a launch. If you want to, you just need to give them different names. For example: 

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "brightscript",
            "request": "launch",
            "name": "BrightScript Debug: Launch",
            "host": "192.168.1.100",
            "password": "password",
            "rootDir": "${workspaceFolder}"
        },
        {
            "type": "brightscript",
            "request": "launch",
            "name": "DIFFERENT_NAME_FOR_TEST_LAUNCH",
            "host": "192.168.1.100",
            "password": "password",
            "rootDir": "${workspaceFolder}"
        }
    ]
}
```

**Comment by georgejecook** [comment]
How do I pass the url args?


On December 9, 2018 at 3:10:55 PM, Bronley Plumb (notifications@github.com)
wrote:

If I understand you correctly, then this is already supported natively in
VSCode. The name field of a launch.json config lets you give a unique name
to a launch. If you want to, you just need to give them different names.
For example:

{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "brightscript",
            "request": "launch",
            "name": "BrightScript Debug: Launch",
            "host": "192.168.1.100",
            "password": "password",
            "rootDir": "${workspaceFolder}"
        },
        {
            "type": "brightscript",
            "request": "launch",
            "name": "DIFFERENT_NAME_FOR_TEST_LAUNCH",
            "host": "192.168.1.100",
            "password": "password",
            "rootDir": "${workspaceFolder}"
        }
    ]
}

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/TwitchBronBron/vscode-brightscript-language/issues/53#issuecomment-445567374>,
or mute the thread

**Comment by TwitchBronBron** [comment]
That sounds like you are asking for deep link support? Which is tracked in [this issue](https://github.com/TwitchBronBron/vscode-brightscript-language/issues/4).

**Comment by georgejecook** [comment]
No, not deep link support; arbitrary launch args. If the DeepLinking ticket
will also resolve that, then good; but they’re not the same thing.


On December 9, 2018 at 3:14:02 PM, Bronley Plumb (notifications@github.com)
wrote:

That sounds like you are asking for deep link support? Which is tracked in this
issue
<https://github.com/TwitchBronBron/vscode-brightscript-language/issues/4>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/TwitchBronBron/vscode-brightscript-language/issues/53#issuecomment-445567601>,
or mute the thread
