### ISSUE TITLE
Problem with Debug Protocol

### ISSUE THREAD

**Issue by jasonbodily** [rokucommunity/vscode-brightscript-language#533]
Type: <b>Bug</b>

Please describe the issue you are experiencing:
Please stop bothering me about the telnet debugger change. I've got it. It's getting annoying.

Steps to reproduce:
Open my project and start it up

Additional feedback:

roku-debug version: 0.20.13
Device firmware: 12.5.0.4178
Debug protocol version: 3.2.0
Device model: 3941X2

Extension version: 2.45.7
VS Code version: Code 1.84.2 (Universal) (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:52:33.687Z)
OS version: Darwin arm64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|32.00GB (2.30GB free)|
|Process Argv|--crash-reporter-id 47a286a6-ffd2-4a04-9bb6-96560022c6ff|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30880072
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30869155
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2cf:30871583
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30885897
pythontbext0:30879054
dsvsc016:30886110
dsvsc017cf:30886113
dsvsc018:30886114
aa_t_chat:30882232

```

</details>

**Comment by jasonbodily** [comment]
Provide a "Do not ask again" option

**Comment by TwitchBronBron** [comment]
You can just update the vscode extension, we disabled the pop-up in the latest release. 

Did you get a chance to test the debug protocol? If so, were there any issues you encountered that need to be addressed?

**Comment by jasonbodily** [comment]
I've been using the VSC debugger for a while and yes it's been helpful. I could use a network inspector more than anything at this point... Thank you for following up.

**Comment by chrisdp** [comment]
We have talked about something like that in the past but it would be a huge task for us to take on. That being said I and other have had a lot of success with Charles Proxy. I have an example here how how you can set it up in your application if you are interested: https://github.com/chrisdp/Roku-Charles-example

**Comment by TwitchBronBron** [comment]
Yeah that would be an awesome addition to the project! We would need to essentially inject a proxy into the project and monitor everything. It could be done, but I agree, the charles proxy is definitely the best option right now. 

Thanks!
