### ISSUE TITLE
support module fuzzy definitions for module/namespacing

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/vscode-brightscript-language#55]
often times, a function will be declared such as 
entitlements_module_getSynchronizePurchaseIds_

and returned in some module object to be invoked such as:
getSynchronizePurchaseIds_

I suggest that until such a time as we can get better scoping, that we filter definitions based on right hand side matches. It might be we include a setting such as modulePrefix which is configurable to `_` or ``, which will be used for a fuzzy definition comparison. That would help drive down false positives, for those of us who use `NAMESPACE_function` module naming conventions.

such as:
pressing f12 on  `m.getSynchronizePurchaseIds_`
will match entitlements_module_getSynchronizePurchaseIds_, because it matched on `_` + `getSynchronizePurchaseIds_`

**Comment by TwitchBronBron** [comment]
So I'm not crazy about adding intellisense for a "convention" of using underscores for namespaces into the project. Ideally, we would wait until we get a parser with actual scoped variable intellisense. 

One thing we can do is reduce or remove false positives, which I'm very open to implementing. 

In our slack discussion, you mentioned this set of code

```brightscript
'myTask.brs
function isOpen()

end function

'myThing.brs
function getSomething()
    return {
          isOpen: myModule.myNamespace_isOpen
    }
end function

'myModule.brs
function createModule()
    module = {}
    module.isOpen= myNamespace_isOpen
    return module
end function

function myNamespace_isOpen()

end function
```

With all of these ways of using them. 
```
a = getSomething().isOpen
isOpen()
m.isOpen = true
a = m.isOpen()
```

Whenever we type any variable followed by a period, a period, we would eliminate all global functions from intellisense. So both `getSomething().` and `m.` would produce no intellisense at all, removing false positives.

**Comment by georgejecook** [comment]
I don't think you understand. This has nothing to do with intellisense. It
pertains to go to definition.

**Comment by georgejecook** [comment]
this was a sily idea. I got control of these projects and fixed the code, not the IDE ;)
