### ISSUE TITLE
VSCode does not exit debug when closing application

### ISSUE THREAD

**Issue by rrirower** [rokucommunity/vscode-brightscript-language#557]
I'm using v2.47.0 and BrighterScript 0.65.27.  If I start my channel in debug, test some things, then click Home to return, the debugger does not exit.  I have to manually close the debug session.

**Comment by TwitchBronBron** [comment]
There's a launch setting called `stopDebuggerOnAppExit`. Try specifically setting it to `true` in your launch.json. Does the debug session close then?
![image](https://github.com/rokucommunity/vscode-brightscript-language/assets/2544493/d455840e-8a6a-43fa-a704-e71c472f38eb)

**Comment by rrirower** [comment]
Thanks.  Adding that line worked.  However, I'm not sure why it stopped working without that line.  Is that setting new?

**Comment by TwitchBronBron** [comment]
It's not a new setting, but we have some inconsistencies between the `default` set in the launch.json compared to in-code. I'm guessing one of them got switched at some point.
