### ISSUE TITLE
Debugger stops at breakpoints I've not set

### ISSUE THREAD

**Issue by rrirower** [rokucommunity/vscode-brightscript-language#559]
After experiencing a program exception in the code while testing, the debugger stops at breakpoints I have not set.  It typically stops at the constructor of a class, or, in the middle of an associative array.  It appears that this may clear up if I reboot my PC and the Roku device.

VSCode: 2.47.0
BSC: 0.65.7

**Comment by rrirower** [comment]
This is pretty "wonky".  I'm not sure what triggers it, but, the debugger will suddenly stop at several breakpoints I have not set.  It's a time suck since I have to step through all of the breakpoints to get to the actual one I have set.

**Comment by TwitchBronBron** [comment]
Hmm. This is pretty strange. Are you using the debug protocol? If so, does this same problem happen when using telnet instead? `"enableDebugProtocol": false`
