### ISSUE TITLE
Default EOL Setting

### ISSUE THREAD

**Issue by Romans-I-XVI** [rokucommunity/vscode-brightscript-language#79]
https://github.com/TwitchBronBron/vscode-brightscript-language/blob/456b4d8146400d4af7bf4bddac10d32ef3cfcfdf/.vscode/settings.json#L15

Is there a reason this setting is here? This makes it so new files default to CRLF line endings where as all of the current project files are using LF.

**Comment by TwitchBronBron** [comment]
Thanks for pointing this out. My desire was to force all new files to have the same line endings. However, in trying to prove that the files were actually saved in CRLF, I realized that was not the case. I think that my GIT install may be normalizing the line endings. I'm using Windows (if you couldn't already tell by the CRLF). When I clone the repo using the GIT cli, my file line endings are CRLF. However, when I download the file directly from GitHub, the line endings are only LF, which is apparently how the files are actually stored.

So I would be open to changing this to just `\n`, or removing it entirely if that would help. What are your thoughts?

**Comment by Romans-I-XVI** [comment]
I think having standardized line endings for the project is good, but I personally would prefer \n. I use Linux, reason I even noticed it was I was all my git diffs were showing a  ^M at the end.

Plus all the files are already formatted that way anyway, might as well keep them in \n. ;)
